version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Sync git submodules
          command: git submodule sync
      - run:
          name: Update git submodules
          command: git submodule update
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the current time
          command: date

