version: 2
jobs:
  build:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run:
          name: Init submodules
          command: git submodule init
      - run:
          name: Update submodules
          command: git submodule update
      - run:
          name: Make files
          command: |
            make
      - run:
          name: run tests
          command: |
            ./all_tests

